GPU is not mandatory for these basic operations

In [1]:
import numpy as np
import torch

## numpy basic

In [2]:
## TO BE COMPLETED

## pytorch basic

In [3]:
x = torch.empty(5,4)
y = torch.rand(5,4)
print(f"The value of x: \n{x} \nThe value of y: \n{y}")
# There is no dtype displayed, meaning the dtype is the default type.

The value of x: 
tensor([[ 1.6381e-42,  1.0141e+31, -3.4111e-38,  3.0702e-41],
        [ 1.6816e-44,  7.2714e+31, -3.4110e-38,  3.0702e-41],
        [ 1.6367e-42,  0.0000e+00, -3.4111e-38,  3.0702e-41],
        [ 1.6816e-44,  8.0533e-42, -3.4111e-38,  3.0702e-41],
        [ 1.6479e-42, -4.4257e-19, -3.4112e-38,  3.0702e-41]]) 
The value of y: 
tensor([[0.7550, 0.0330, 0.7722, 0.9595],
        [0.3703, 0.8375, 0.8398, 0.8110],
        [0.4777, 0.3329, 0.0829, 0.7412],
        [0.6782, 0.0648, 0.4949, 0.2766],
        [0.6909, 0.3150, 0.3087, 0.8144]])


In [4]:
torch.get_default_dtype()
# torch.set_default_dtype(torch.float64).
# Other frequently used dtypes include: float(float32), double(float64), int(int32), long(int64).

torch.float32

In [5]:
x = torch.rand(5,3)
y = torch.randn(5,3)
print(f"{x}\n{y}")
# rand() returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).
# randn() returns ..... from a normal distribution with mean 0 and variance 1.

tensor([[0.9441, 0.1776, 0.0830],
        [0.9816, 0.4427, 0.8612],
        [0.2543, 0.0445, 0.1895],
        [0.4997, 0.4137, 0.7272],
        [0.6192, 0.4530, 0.6524]])
tensor([[-1.2967,  0.4489, -0.5985],
        [-0.8963, -0.0285,  1.4822],
        [ 0.3001,  0.5019,  0.1306],
        [ 1.5064, -0.2875,  0.6730],
        [-0.6206,  0.2029,  0.4886]])


In [6]:
x = torch.ones(3, dtype=torch.double)
x

tensor([1., 1., 1.], dtype=torch.float64)

In [7]:
x = torch.ones(4,6, dtype=torch.double)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.3377, -1.8835, -0.2360,  0.7680, -0.1798, -2.3429],
        [ 0.4253, -3.1057, -0.6039,  0.5638,  0.6197,  0.0444],
        [-1.2050, -2.4951, -0.9874,  0.0374,  1.0409,  0.2464],
        [ 1.9877, -0.6088, -0.7522,  1.4917,  0.3998, -0.5291]])

In [9]:
x.size()
# A little bit different in np.

torch.Size([4, 6])

In [10]:
# Again, dtype of x is the default one, so it's not displayed.
x.dtype

torch.float32

In [11]:
x = torch.randn(4, 4)
# Reshape original tensor
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Conversion between np and torch

In [12]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [13]:
a = np.ones(5)
b = torch.from_numpy(a)
b
# hmmmm... Seems like the default dtype in np is long(float64)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

## Types of tensor

* dim = 0 --> scalar
* dim = 1 --> vector
* dim = 2 --> matrix
* dim >= 3 --> n-dimensional tensor



### Scalar

In [14]:
# interesting details
x = torch.tensor(30)
y = torch.tensor(30.)
z = torch.tensor(30, dtype=torch.int)

In [15]:
# why interesting? let's check their dtype!
print(f"The dtype of x: {x.dtype}, y: {y.dtype}, z: {z.dtype}")

The dtype of x: torch.int64, y: torch.float32, z: torch.int32


In [16]:
# type conversion
x = x.type(torch.float)
x.dtype

torch.float32

In [17]:
x.dim()

0

In [18]:
x

tensor(30.)

In [19]:
# Returns the value of this tensor as a standard Python number. This only works for tensors with one element.
# For more than one element, use tolist()
x.item()

30.0

### Vector

In [20]:
# Can treat this as the feature of one data. Eg. the word embedding of 'hello'.
v = torch.tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [21]:
v.dim()

1

In [22]:
v.size()

torch.Size([3])

In [23]:
# here cannot use item(). item() is only used for scalar.
v.tolist()

[1.5, -0.5, 3.0]

### Matrix

In [24]:
# can be treated as a 2D image, or a series of data Eg. the embedding of 'hello' and 'bye'.
M = torch.tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [25]:
# Frequently used operations:
# TO BE COMPLETED