GPU is not mandatory for these basic operations

In [1]:
import numpy as np
import torch

## numpy basic

In [2]:
## TO BE COMPLETED

## pytorch basic

In [3]:
x = torch.empty(5,4)
y = torch.rand(5,4)
print(f"The value of x: \n{x} \nThe value of y: \n{y}")
# There is no dtype displayed, meaning the dtype is the default type.

The value of x: 
tensor([[1.6816e-44, 6.5650e+28, 1.1494e+21, 3.1486e-41],
        [1.6367e-42, 7.9311e+34, 1.1495e+21, 3.1486e-41],
        [1.6816e-44, 7.3975e+20, 1.1495e+21, 3.1486e-41],
        [1.6479e-42, 1.9603e-19, 1.1495e+21, 3.1486e-41],
        [2.2421e-44, 8.3856e-33, 0.0000e+00, 0.0000e+00]]) 
The value of y: 
tensor([[0.5849, 0.8643, 0.1645, 0.7744],
        [0.0140, 0.6649, 0.2596, 0.4887],
        [0.3611, 0.9237, 0.1337, 0.1028],
        [0.3316, 0.3511, 0.8402, 0.6044],
        [0.6118, 0.7639, 0.9137, 0.0073]])


In [4]:
torch.get_default_dtype()
# torch.set_default_dtype(torch.float64).
# Other frequently used dtypes include: float(float32), double(float64), int(int32), long(int64).

torch.float32

In [5]:
x = torch.rand(5,3)
y = torch.randn(5,3)
print(f"{x}\n{y}")
# rand() returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).
# randn() returns ..... from a normal distribution with mean 0 and variance 1.

tensor([[0.4391, 0.4834, 0.1794],
        [0.1733, 0.4383, 0.5415],
        [0.7768, 0.0784, 0.1916],
        [0.9708, 0.8035, 0.6229],
        [0.2296, 0.2791, 0.7258]])
tensor([[ 0.5605,  0.9475, -1.3042],
        [ 0.6637,  1.1219, -0.4261],
        [-2.1299, -1.6804,  1.8108],
        [-0.1365,  1.1169,  0.5585],
        [-0.3357,  0.0447,  0.2542]])


In [6]:
x = torch.ones(3, dtype=torch.double)
x

tensor([1., 1., 1.], dtype=torch.float64)

In [7]:
x = torch.ones(4,6, dtype=torch.double)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.8787, -1.3302, -0.5055,  1.7225, -0.0877, -0.4710],
        [ 0.9442,  1.0059, -0.2730,  2.7424,  0.1473, -0.7858],
        [ 1.2892, -0.8139, -0.8446, -0.7798,  0.1715,  0.4134],
        [ 0.1211, -0.8572, -0.1017,  1.3049, -1.1889, -2.5047]])

In [9]:
x.size()
# A little bit different in np.

torch.Size([4, 6])

In [10]:
# Again, dtype of x is the default one, so it's not displayed.
x.dtype

torch.float32

In [11]:
x = torch.randn(4, 4)
# Reshape original tensor
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Conversion between np and torch

In [12]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [13]:
a = np.ones(5)
b = torch.from_numpy(a)
b
# hmmmm... Seems like the default dtype in np is long(float64)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)